require("dotenv").config();
const express = require("express");
const cors = require('cors');
const app = express();
app.use(cors());
const PORT = 3012;
app.use(express.json());
const albumsRoutes=require("./server/routes/albumsRoutes");
const commentsRoutes=require("./server/routes/CommentsRoutes");
const photosRoutes=require("./server/routes/photoRoutes");
const postsRoutes=require("./server/routes/postsRoutes");
const registrationRoutes=require("./server/routes/registrationRoutes");
const todosRoutes=require("./server/routes/todosRoutes");
app.use("/albums",albumsRoutes);
app.use('/comments',commentsRoutes);
app.use("/posts",postsRoutes);
app.use("/photos",photosRoutes);
app.use('/todos',todosRoutes);
app.use('/registration',registrationRoutes);
app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`);
});
