require("dotenv").config();
const express = require("express");
const cors = require('cors');
const app = express();
app.use(cors());
const PORT = 3012;
app.use(express.json());
const albumsRoutes=require("./BL/routes/albumsRoutes");
const commentsRoutes=require("./BL/routes/CommentsRoutes");
const photosRoutes=require("./BL/routes/photosRoutes");
const postsRoutes=require("./BL/routes/postsRoutes");
const registrationRoutes = require("./BL/routes/registrationRoutes");
const todosRoutes = require("./BL/routes/todosRoutes");
app.use("/albums",albumsRoutes);
app.use('/comments',commentsRoutes);
app.use("/posts",postsRoutes);
app.use("/photos",photosRoutes);
app.use('/todos', todosRoutes);
app.use('/registration', registrationRoutes);
app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`);
});
